<template>
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><NuxtLink to="/workspaces" class="text-sm text-indigo-600 dark:text-indigo-400">← All workspaces</NuxtLink><AppLoadingSpinner v-if="workspacesStore.loading && !workspace" class="mt-8" /><template v-else-if="workspace"><div class="mt-4 flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">{{ workspace.name }}</h1><p class="mt-1 text-gray-500">{{ workspace.description || 'No description' }}</p><p class="mt-2 text-sm text-gray-500">Your role: <strong>{{ role }}</strong></p></div><NuxtLink class="btn-primary self-start" :to="`/todos?workspace=${workspace._id}`">Open todos</NuxtLink></div><section v-if="role === 'owner'" class="card mt-8"><h2 class="font-semibold text-gray-900 dark:text-white">Invite member</h2><form class="mt-4 flex flex-col sm:flex-row gap-3" @submit.prevent="invite"><input v-model.trim="inviteForm.email" type="email" required class="input flex-1" placeholder="Registered user's email" /><select v-model="inviteForm.role" class="input sm:w-36"><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button class="btn-primary" :disabled="inviting">Invite</button></form><p v-if="inviteError" class="mt-2 text-sm text-red-600">{{ inviteError }}</p></section><section class="mt-8"><h2 class="font-semibold text-gray-900 dark:text-white mb-3">Members</h2><div class="space-y-3"><div v-for="member in workspace.members" :key="member.user._id" class="card flex flex-wrap items-center justify-between gap-3"><div><p class="font-medium text-gray-900 dark:text-white">{{ member.user.name || member.user.username }}</p><p class="text-sm text-gray-500">@{{ member.user.username }}</p></div><div class="flex items-center gap-2"><span v-if="role !== 'owner' || member.role === 'owner'" class="badge bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-200">{{ member.role }}</span><template v-else><select class="input py-1 text-sm" :value="member.role" @change="changeRole(member.user._id, ($event.target as HTMLSelectElement).value)"><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button class="text-sm text-red-600 hover:underline" @click="remove(member.user._id)">Remove</button></template></div></div></div></section><section class="card mt-8 text-sm text-gray-600 dark:text-gray-300"><h2 class="font-semibold text-gray-900 dark:text-white mb-2">Role permissions</h2><p><strong>Owner:</strong> manages members and every todo. <strong>Editor:</strong> creates and manages only their own todos. <strong>Viewer:</strong> can view workspace todos only.</p></section></template></div>
</template>
<script setup lang="ts">
import { useWorkspacesStore, type WorkspaceDetail, type WorkspaceRole } from '~/stores/workspaces'
import { useToast } from '~/composables/useToast'
definePageMeta({ middleware: 'auth', layout: 'default' }); useHead({ title: 'Workspace' })
const route = useRoute(); const workspacesStore = useWorkspacesStore(); const toast = useToast(); const workspace = ref<WorkspaceDetail | null>(null); const role = ref<WorkspaceRole | null>(null); const inviting = ref(false); const inviteError = ref(''); const inviteForm = reactive({ email: '', role: 'editor' as 'editor' | 'viewer' })
const message = (error: any) => error?.data?.message || error?.message || 'The request could not be completed.'
const load = async () => { try { const result = await workspacesStore.fetchWorkspace(String(route.params.id)); workspace.value = result; role.value = result.role } catch (error) { toast.error(message(error)); await navigateTo('/workspaces') } }
const invite = async () => { inviteError.value = ''; inviting.value = true; try { await workspacesStore.inviteMember(String(route.params.id), inviteForm); inviteForm.email = ''; toast.success('Invitation created.'); } catch (error) { inviteError.value = message(error) } finally { inviting.value = false } }
const changeRole = async (memberId: string, nextRole: string) => { try { await workspacesStore.updateMemberRole(String(route.params.id), memberId, nextRole as 'editor' | 'viewer'); workspace.value = workspacesStore.activeWorkspace; toast.success('Role updated.'); } catch (error) { toast.error(message(error)) } }
const remove = async (memberId: string) => { if (!confirm('Remove this member?')) return; try { await workspacesStore.removeMember(String(route.params.id), memberId); workspace.value = workspacesStore.activeWorkspace; toast.success('Member removed.'); } catch (error) { toast.error(message(error)) } }
onMounted(load)
</script>
