<template>
  <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="flex flex-wrap items-center justify-between gap-4 mb-8"><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">Workspaces</h1><p class="text-sm text-gray-500">Keep personal work and team collaboration separate.</p></div><button class="btn-primary" @click="showCreate = !showCreate">➕ Create team workspace</button></div>
    <form v-if="showCreate" class="card mb-6 grid gap-3" @submit.prevent="createWorkspace"><input v-model.trim="newWorkspace.name" class="input" required minlength="2" maxlength="80" placeholder="Workspace name" /><textarea v-model.trim="newWorkspace.description" class="input min-h-24" maxlength="300" placeholder="Description (optional)" /><p v-if="formError" class="text-sm text-red-600">{{ formError }}</p><div class="flex gap-3"><button class="btn-primary" :disabled="creating">Create</button><button type="button" class="btn-outline" @click="showCreate = false">Cancel</button></div></form>
    <AppLoadingSpinner v-if="workspacesStore.loading" />
    <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-4"><article v-for="workspace in workspacesStore.workspaces" :key="workspace._id" class="card"><div class="flex justify-between gap-3"><div><h2 class="font-semibold text-gray-900 dark:text-white">{{ workspace.name }}</h2><p class="mt-1 text-sm text-gray-500">{{ workspace.description || (workspace.type === 'personal' ? 'Your private workspace' : 'Team collaboration workspace') }}</p></div><span class="badge bg-indigo-50 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300">{{ workspace.type }}</span></div><p class="mt-4 text-xs text-gray-500">{{ workspace.memberCount }} member{{ workspace.memberCount === 1 ? '' : 's' }} · Your role: <strong>{{ workspace.role }}</strong></p><div class="mt-4 flex gap-3"><NuxtLink class="btn-primary text-sm" :to="`/todos?workspace=${workspace._id}`">Open todos</NuxtLink><NuxtLink v-if="workspace.type === 'team'" class="btn-outline text-sm" :to="`/workspaces/${workspace._id}`">Manage</NuxtLink></div></article></div>
    <section v-if="workspacesStore.invitations.length" class="mt-10"><h2 class="font-semibold text-gray-900 dark:text-white mb-3">Pending invitations</h2><div class="space-y-3"><div v-for="invitation in workspacesStore.invitations" :key="invitation._id" class="card flex flex-wrap items-center justify-between gap-3"><p class="text-sm dark:text-gray-200"><strong>{{ invitation.inviter.name || invitation.inviter.username }}</strong> invited you to <strong>{{ invitation.workspace.name }}</strong> as {{ invitation.role }}.</p><div class="flex gap-2"><button class="btn-primary text-sm" @click="respond(invitation._id, true)">Accept</button><button class="btn-outline text-sm" @click="respond(invitation._id, false)">Decline</button></div></div></div></section>
  </div>
</template>
<script setup lang="ts">
import { useWorkspacesStore } from '~/stores/workspaces'
import { useToast } from '~/composables/useToast'
definePageMeta({ middleware: 'auth', layout: 'default' }); useHead({ title: 'Workspaces' })
const workspacesStore = useWorkspacesStore(); const toast = useToast(); const showCreate = ref(false); const creating = ref(false); const formError = ref(''); const newWorkspace = reactive({ name: '', description: '' })
const message = (error: any) => error?.data?.message || error?.message || 'The request could not be completed.'
const createWorkspace = async () => { formError.value = ''; creating.value = true; try { await workspacesStore.createWorkspace(newWorkspace); newWorkspace.name = ''; newWorkspace.description = ''; showCreate.value = false; toast.success('Team workspace created.'); } catch (error) { formError.value = message(error) } finally { creating.value = false } }
const respond = async (id: string, accept: boolean) => { try { await workspacesStore.respondToInvitation(id, accept); toast.success(accept ? 'Invitation accepted.' : 'Invitation declined.'); } catch (error) { toast.error(message(error)) } }
onMounted(async () => { try { await Promise.all([workspacesStore.fetchWorkspaces(), workspacesStore.fetchInvitations()]) } catch (error) { toast.error(message(error)) } })
</script>
